### ISSUE TITLE
make app display more intuitive

### ISSUE THREAD

**Issue by bluens** [jusjusjus/wxArt#17]
- video should be a mode
  - recording should be indicated somehow
  - options should change according to mode
  -  video is not centralized
  - video disappears when frames are generated
  - generation of video can not be canceled
- similar issues for photo mode
  - photos may be taken with two different buttons?
  - computation can not be canceled
  - style composition is overall confusing

**Comment by bluens** [comment]
I will tackle these problems today and see what I can do...

**Comment by jusjusjus** [comment]
I can comment on what I think is easy to accomplish:
Easy subtasks:
- video disappears when frames are generated
- photos may be taken with two different buttons?

Wegen den modi, die du ansprichst:  Das ist eher was zum verzetteln.

Anmerkung:  Nicht auf master arbeiten!

**Comment by bluens** [comment]
Keine Sorge, ich hatte nicht vor aus master zu arbeiten.

Jeder fix dieser kleinen Probleme kommt mir wie ein hack vor.
Auch sind einige Kommentare obsolet, andere fehlen. 

Ich versuch erstmal zu verstehen, was das Programm macht ;).

**Comment by jusjusjus** [comment]
> Auch sind einige Kommentare obsolet, andere fehlen.

Python ist selten kommentiert.

**Comment by bluens** [comment]
Google makes nice suggestions when it comes to python comments
https://google.github.io/styleguide/pyguide.html

**Comment by bluens** [comment]
talked to jusjusjus:
"hacking better than implementing new design cause no time"
I ask all contributers to hack like a häcksler!

**Comment by bluens** [comment]
Closed? Nice

**Comment by jusjusjus** [comment]
I don't think video should be a mode.  It may be just a button that starts a video.

Indication of recording is now a separate new Issue.

Video is not centralized:  This may be a copy of Issue #10.

Video disappears when frames are generated: The GIF widget switches mode to showing a static bitmap when by a call to stop (artwork.py:89).

generation of video can not be canceled.  Generation of video can be cancelled.  Wait for the widget to regain control.

For Photos:
photos may be taken with two different buttons?:  Why not?

computation can not be canceled.  Typically the computation time of a single picture is 2 seconds on the machine for the 3. October.  I don't think this feature is necessary.

style composition is overall confusing:  I opened a new issue.  We will need more information as to what you think is the source of the confusion.
