### ISSUE TITLE
Layout of user interface

### ISSUE THREAD

**Issue by jusjusjus** [jusjusjus/wxArt#21]
The style composition was described as overall confusing.

**Comment by jusjusjus** [comment]
Wie wär's die Buttons größe zu machen und unter des artwork zu tun, !wenn keine e-mail da ist!?

**Comment by bluens** [comment]
Can't figure out how to stop button from freezing (photo mode), a feature that is unwanted in this version, without breaking program.
No consistent way of making button stop what it is doing.
Just commenting everything that stops button results in broken video and photo stream.
